version: '3'

services:
  database:
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 220698
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - pgdata:/var/lib/postgresql/data


  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2182:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "alerts:1:3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata: